server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .html
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG